name: Deploy To Staging

on:
  # This will run whenever code is merged/pushed into main
  # Deploys to staging and Render Hook is triggered to staging environment
  # e2e tests can be run here - https://friends-without-benefits-1.onrender.com
  pull_request:
    branches:
      - staging

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from main
        run: |
          echo "Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          if [[ "${{ github.event.pull_request.head.ref }}" != "main" ]]; then
            echo "❌ This PR is not coming from the 'main' branch. Exiting..."
            exit 1
          fi
          echo "✅ This PR is correctly coming from the 'main' branch. Continuing..."

      - uses: actions/checkout@v4
      - name: Install Project Dependencies
        run: |
          npm install && npm run setup

      - name: Build App
        run: npm run render-build

      - name: Deploy to Staging
        env:
          STAGING_WEBHOOK: ${{ secrets.RENDER_STAGING_DEPLOY_HOOK_URL }}
        run: |
          # WebHook to trigger deployment to Render Staging Environment
          curl "$STAGING_WEBHOOK"

      - name: Wait for Deployment
        run: sleep 180s

      - name: Run Cypress E2E Tests
        run: npx cypress run --e2e
        env:
          CYPRESS_STAGING_BASE_URL: https://friends-without-benefits-1.onrender.com

      - name: Run Component Tests
        run: echo "Component Testing on the Deployed Site Starts Here"
