name: Develop to Testing

on:
  # Auto-triggered action when dev branch is updated/pulled to testing
  pull_request:
    branches:
      - "testing"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from develop
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
            echo "This PR is not from develop, exiting..."
            exit 1
          fi
          echo "This PR is from develop, continuing..."

      - uses: actions/checkout@v4
      - name: Install Project Dependencies
        run: |
          npm install && npm run setup

      - name: Build App
        run: npm run render-build

      - name: Start Tests
        run: echo "Component Testing"
