name: Feature Branch CI

on:
  # Will run whenever a push to a feature branch happens
  # or when a pull request is made from a feature branch into develop
  pull_request:
    branches:
      - "develop"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from a feature/** branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "feature/**" ]]; then
            echo "This PR is not from feature/**, exiting..."
            exit 1
          fi
          echo "This PR is from feature/**, continuing..."

      - uses: actions/checkout@v4
      - name: Install Project Dependencies
        run: |
          npm install && npm run setup

      - name: Build App
        run: npm run render-build

        # TEST: Preform LINTING on CLIENT

      - name: Lint Client
        run: npm run lint:client
