name: QA Testing

on:
  push:
    branches:
      - "testing"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Project Dependencies
        run: |
          npm install && npm run setup

      - name: Build App
        run: npm run render-build

        # Add the tests here once Cypress is integrated
      - name: Testing Actions
        run: echo "Testing Actions Completed"

      - name: Create Pull Request to main
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          head: "testing"
          title: "Auto PR: testing → main"
          body: "Automated PR from testing to main after passing QA checks."
          branch: "auto/testing-to-main"
